/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2c1700",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed": "#d6e3ff",
        "inverse-surface": "#303033",
        "on-primary-fixed": "#071b37",
        "tertiary-container": "#361d00",
        "surface-container-low": "#f5f3f6",
        "outline": "#75777e",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dae2ff",
        "error-container": "#ffdad6",
        "surface-tint": "#4d5f7e",
        "on-surface-variant": "#44474d",
        "primary-fixed-dim": "#b5c7eb",
        "on-secondary-fixed": "#001847",
        "on-primary-container": "#798bac",
        "surface-bright": "#fbf9fb",
        "surface-container-high": "#e9e7ea",
        "secondary-container": "#2d6deb",
        "secondary-fixed-dim": "#b1c5ff",
        "secondary": "#0054cb",
        "surface-dim": "#dbd9dc",
        "surface-variant": "#e4e2e5",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#c5c6ce",
        "surface-container": "#efedf0",
        "on-secondary-fixed-variant": "#0040a0",
        "on-tertiary-fixed-variant": "#60401d",
        "primary-container": "#10233f",
        "tertiary": "#180a00",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2e5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcbc",
        "surface": "#fbf9fb",
        "primary": "#000d23",
        "on-surface": "#1b1b1e",
        "on-background": "#1b1b1e",
        "on-primary-fixed-variant": "#364765",
        "background": "#fbf9fb",
        "on-tertiary-container": "#aa8259",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b5c7eb",
        "tertiary-fixed-dim": "#ecbe90",
        "inverse-on-surface": "#f2f0f3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "32px",
        "xl": "48px",
        "base": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "sora": ["Sora", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
